version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragpass}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    ports:
      - "1234:1234"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn app.api.server:app --host 0.0.0.0 --port 8000 --reload
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant

  streamlit:
    build: .
    command: streamlit run app/main.py --server.port 8501 --server.headless true
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - postgres
      - qdrant

volumes:
  qdrant_storage:
  pgdata:
  